name: Deploy S3 + CloudFront Website (Terraform)

on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: AWS/Project-03/terraform
    steps:
      - name: Debug network
        run: |
          echo "testing DNS.."
          nslookup registry.terraform.io || true
          echo " testing HTTPS.."
          curl -I
          https://registory.terraform.io || true 
          curl -I
          htpps://releases.hashicorp.com || true
        
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Show repo structure
        run: |
         pwd 
         ls -la
         ls -la AWS
         find AWS -maxdepth 4 -type d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: AWS/Project-03/terraform
        run: terraform init 
        env:
         TF_REGISTRY_CLIENT_TIMEOUT: "30"

      - name: Terraform Validate
        working-directory: AWS/Project-03/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: AWS/Project-03/terraform
        run: terraform plan

      # Apply ONLY if you want auto-deploy
      - name: Terraform Apply
        working-directory: AWS/Project-03/terraform
        run: terraform apply -auto-approve

     
